DROP SEQUENCE sec_empleados;
DROP SEQUENCE sec_clientes;
DROP SEQUENCE sec_proyectos;
DROP SEQUENCE sec_eventos;
DROP SEQUENCE sec_empresas;
DROP SEQUENCE sec_menus;
DROP SEQUENCE sec_platos;
DROP SEQUENCE sec_alergenos;
DROP SEQUENCE sec_invitados;

CREATE SEQUENCE sec_empleados
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_empleado
BEFORE INSERT ON empleados
FOR EACH ROW
BEGIN
    SELECT sec_empleados.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

CREATE SEQUENCE sec_clientes
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_cliente
BEFORE INSERT ON clientes
FOR EACH ROW
BEGIN
    SELECT sec_clientes.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

CREATE SEQUENCE sec_proyectos
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_proyecto
BEFORE INSERT ON proyectos
FOR EACH ROW
BEGIN
    SELECT sec_proyectos.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

CREATE SEQUENCE sec_eventos
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_evento
BEFORE INSERT ON eventos
FOR EACH ROW
BEGIN
    SELECT sec_eventos.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

CREATE SEQUENCE sec_empresas
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_empresa
BEFORE INSERT ON empresas
FOR EACH ROW
BEGIN
    SELECT sec_empresas.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

CREATE SEQUENCE sec_menus
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_menu
BEFORE INSERT ON menus
FOR EACH ROW
BEGIN
    SELECT sec_menus.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

CREATE SEQUENCE sec_platos
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_plato
BEFORE INSERT ON platos
FOR EACH ROW
BEGIN
    SELECT sec_platos.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

CREATE SEQUENCE sec_alergenos
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_alergeno
BEFORE INSERT ON alergenos
FOR EACH ROW
BEGIN
    SELECT sec_alergenos.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/

CREATE SEQUENCE sec_invitados
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

CREATE OR REPLACE TRIGGER crear_id_invitado
BEFORE INSERT ON invitados
FOR EACH ROW
BEGIN
    SELECT sec_invitados.NEXTVAL INTO :NEW.id FROM DUAL;
END;
/